export const PATHS = {
  PUBLIC: {
    HOME: '/',
  },
  AUTH: {
    LOGIN: '/login',
  },
  SUPER_ADMIN: {
    ROOT: '/admin',
    OVERVIEW: '/admin/overview',
    ORGANIZATIONS: '/admin/organizations',
    ORGANIZATION_DETAIL: '/admin/organizations/:organizationId',
    ORGANIZATION_DETAIL_BUILD: (id: string) => `/admin/organizations/${id}`,
    ORGANIZATION_MEMBERSHIPS:
      '/admin/organizations/:organizationId/memberships',
    ORGANIZATION_MEMBERSHIPS_BUILD: (id: string) =>
      `/admin/organizations/${id}/memberships`,
    STORE_LIST: '/admin/organizations/:organizationId/stores',
    STORE_LIST_BUILD: (orgId: string) => `/admin/organizations/${orgId}/stores`,
    STORE_CREATE: '/admin/organizations/:organizationId/stores/new',
    STORE_CREATE_BUILD: (orgId: string) =>
      `/admin/organizations/${orgId}/stores/new`,
    ALLERGENS: '/admin/allergens',
    DIETARY_MARKERS: '/admin/dietary-markers',
  },
  STOREFRONT: {
    LANDING: '/s/:storeId',
    LANDING_BUILD: (storeId: string) => `/s/${storeId}`,
    JOIN_ENTRY: '/s/:storeId/join',
    JOIN_ENTRY_BUILD: (storeId: string) => `/s/${storeId}/join`,
    JOIN: '/s/:storeId/join/:joinCode',
    JOIN_BUILD: (storeId: string, joinCode: string) =>
      `/s/${storeId}/join/${joinCode}`,
    MENU: '/s/:storeId/menu',
    MENU_BUILD: (storeId: string) => `/s/${storeId}/menu`,
    INVITE: '/s/:storeId/invite',
    INVITE_BUILD: (storeId: string) => `/s/${storeId}/invite`,
    CART: '/s/:storeId/cart',
    CART_BUILD: (storeId: string) => `/s/${storeId}/cart`,
    ORDER_HISTORY: '/s/:storeId/orders',
    ORDER_HISTORY_BUILD: (storeId: string) => `/s/${storeId}/orders`,
    ORDER: '/s/:storeId/orders/:orderId',
    ORDER_BUILD: (storeId: string, orderId: string) =>
      `/s/${storeId}/orders/${orderId}`,
  },
  MERCHANT: {
    ROOT: '/merchant',
    SELECT_ORG: '/merchant/select-org',
    SELECT_STORE: '/merchant/select-store',
    MENU: '/merchant/menu',
    MENU_CREATE: '/merchant/menu/new',
    MENU_DETAIL: '/merchant/menu/:productId',
    MENU_DETAIL_BUILD: (id: string) => `/merchant/menu/${id}`,
    ORDERS: '/merchant/orders',
    ORDER_DETAIL: '/merchant/orders/:orderId',
    ORDER_DETAIL_BUILD: (orderId: string) => `/merchant/orders/${orderId}`,
    STORE_SETTINGS: '/merchant/store-settings',
    CATEGORIES: '/merchant/categories',
    MODIFIERS: '/merchant/modifiers',
    MODIFIER_CREATE: '/merchant/modifiers/new',
    MODIFIER_DETAIL: '/merchant/modifiers/:modifierId',
    MODIFIER_DETAIL_BUILD: (id: string) => `/merchant/modifiers/${id}`,
    TAGS: '/merchant/tags',
  },
} as const;
